### ISSUE TITLE
Is there something wrong with the iptables (log) rules?

### ISSUE THREAD

**Issue by wbartels** [Adamm00/IPSet_ASUS#51]
###### Brief Description Of Issue
After installing Skynet or Skynet Lite (witch uses the same iptables rules) DROP's like below are not logged anymore:
```
Oct 12 20:24:53 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=123.14.87.235 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=51 ID=60536 PROTO=TCP SPT=1361 DPT=23 SEQ=1411206384 ACK=0 WINDOW=5219 RES=0x00 SYN URGP=0 
Oct 12 20:25:00 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=106.75.13.173 DST=xxx.xxx.xxx.xxx LEN=44 TOS=0x00 PREC=0x00 TTL=240 ID=2520 PROTO=TCP SPT=58914 DPT=67 SEQ=124601707 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 OPT (02040584) 
Oct 12 20:25:05 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=78.154.18.99 DST=xxx.xxx.xxx.xxx LEN=134 TOS=0x00 PREC=0x00 TTL=118 ID=18017 PROTO=UDP SPT=53009 DPT=53803 LEN=114 
Oct 12 20:25:15 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=17.57.144.4 DST=xxx.xxx.xxx.xxx LEN=105 TOS=0x00 PREC=0x00 TTL=50 ID=37681 DF PROTO=TCP SPT=443 DPT=63528 SEQ=2602349115 ACK=3283063853 WINDOW=303 RES=0x00 ACK PSH URGP=0 OPT (0101080AA0CCBD7131E0B961) 
Oct 12 20:25:15 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=192.241.218.169 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=54321 PROTO=TCP SPT=57102 DPT=264 SEQ=351579914 ACK=0 WINDOW=65535 RES=0x00 SYN URGP=0 
Oct 12 20:25:23 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=81.16.206.8 DST=xxx.xxx.xxx.xxx LEN=131 TOS=0x00 PREC=0x00 TTL=110 ID=33991 PROTO=UDP SPT=38562 DPT=53803 LEN=111 
Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=244 ID=47919 DF PROTO=TCP SPT=443 DPT=64503 SEQ=642779507 ACK=3902175720 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1EDC158231E137A2) 
Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=244 ID=57875 DF PROTO=TCP SPT=443 DPT=64501 SEQ=2290861553 ACK=375851874 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1EDBF12831E137A9) 
Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=243 ID=18281 DF PROTO=TCP SPT=443 DPT=64504 SEQ=3157486796 ACK=3061319390 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1E9C064331E137A8) 
Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=244 ID=29493 DF PROTO=TCP SPT=443 DPT=64502 SEQ=2109640064 ACK=3010256920 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1ED1090E31E13836) 
Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=35.244.181.201 DST=xxx.xxx.xxx.xxx LEN=115 TOS=0x00 PREC=0x80 TTL=60 ID=10133 PROTO=TCP SPT=443 DPT=64499 SEQ=9698972 ACK=3074473230 WINDOW=277 RES=0x00 ACK PSH URGP=0 OPT (0101080AE2B791A531E13849) 
Oct 12 20:25:29 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25061 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
Oct 12 20:25:29 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25062 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
Oct 12 20:25:29 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25063 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
Oct 12 20:25:30 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=5.189.187.90 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=57 ID=60572 DF PROTO=UDP SPT=6938 DPT=53803 LEN=105 
Oct 12 20:25:30 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25064 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
Oct 12 20:25:31 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25065 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0
```
Also port scans are not logged anymore for example:
ShieldUP! https://www.grc.com/x/ne.dll?bh0bkyd2

After uninstall Skynet/Skynet Lite and reboot port scans are logged again.
I hope this can be fixed! (I had the idea to scan the logfile for **kernel: DROP** and make an auto block-list that will automatically expire after a certain time interval)

Thanks,

Willem Bartels

**Comment by Adamm00** [comment]
> After installing Skynet or Skynet Lite (witch uses the same iptables rules) DROP's like below are not logged anymore:
> 
> ```
> Oct 12 20:24:53 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=123.14.87.235 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=51 ID=60536 PROTO=TCP SPT=1361 DPT=23 SEQ=1411206384 ACK=0 WINDOW=5219 RES=0x00 SYN URGP=0 
> Oct 12 20:25:00 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=106.75.13.173 DST=xxx.xxx.xxx.xxx LEN=44 TOS=0x00 PREC=0x00 TTL=240 ID=2520 PROTO=TCP SPT=58914 DPT=67 SEQ=124601707 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 OPT (02040584) 
> Oct 12 20:25:05 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=78.154.18.99 DST=xxx.xxx.xxx.xxx LEN=134 TOS=0x00 PREC=0x00 TTL=118 ID=18017 PROTO=UDP SPT=53009 DPT=53803 LEN=114 
> Oct 12 20:25:15 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=17.57.144.4 DST=xxx.xxx.xxx.xxx LEN=105 TOS=0x00 PREC=0x00 TTL=50 ID=37681 DF PROTO=TCP SPT=443 DPT=63528 SEQ=2602349115 ACK=3283063853 WINDOW=303 RES=0x00 ACK PSH URGP=0 OPT (0101080AA0CCBD7131E0B961) 
> Oct 12 20:25:15 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=192.241.218.169 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=54321 PROTO=TCP SPT=57102 DPT=264 SEQ=351579914 ACK=0 WINDOW=65535 RES=0x00 SYN URGP=0 
> Oct 12 20:25:23 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=81.16.206.8 DST=xxx.xxx.xxx.xxx LEN=131 TOS=0x00 PREC=0x00 TTL=110 ID=33991 PROTO=UDP SPT=38562 DPT=53803 LEN=111 
> Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=244 ID=47919 DF PROTO=TCP SPT=443 DPT=64503 SEQ=642779507 ACK=3902175720 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1EDC158231E137A2) 
> Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=244 ID=57875 DF PROTO=TCP SPT=443 DPT=64501 SEQ=2290861553 ACK=375851874 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1EDBF12831E137A9) 
> Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=243 ID=18281 DF PROTO=TCP SPT=443 DPT=64504 SEQ=3157486796 ACK=3061319390 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1E9C064331E137A8) 
> Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=143.204.94.49 DST=xxx.xxx.xxx.xxx LEN=83 TOS=0x00 PREC=0x00 TTL=244 ID=29493 DF PROTO=TCP SPT=443 DPT=64502 SEQ=2109640064 ACK=3010256920 WINDOW=123 RES=0x00 ACK PSH URGP=0 OPT (0101080A1ED1090E31E13836) 
> Oct 12 20:25:24 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=35.244.181.201 DST=xxx.xxx.xxx.xxx LEN=115 TOS=0x00 PREC=0x80 TTL=60 ID=10133 PROTO=TCP SPT=443 DPT=64499 SEQ=9698972 ACK=3074473230 WINDOW=277 RES=0x00 ACK PSH URGP=0 OPT (0101080AE2B791A531E13849) 
> Oct 12 20:25:29 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25061 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
> Oct 12 20:25:29 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25062 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
> Oct 12 20:25:29 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25063 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
> Oct 12 20:25:30 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=5.189.187.90 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=57 ID=60572 DF PROTO=UDP SPT=6938 DPT=53803 LEN=105 
> Oct 12 20:25:30 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25064 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0 
> Oct 12 20:25:31 kernel: DROP IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=40.101.18.242 DST=xxx.xxx.xxx.xxx LEN=1160 TOS=0x00 PREC=0x00 TTL=244 ID=25065 DF PROTO=TCP SPT=443 DPT=52050 SEQ=4080673919 ACK=2637222893 WINDOW=2053 RES=0x00 ACK PSH URGP=0
> ```
> 
> Also port scans are not logged anymore for example:
> ShieldUP! https://www.grc.com/x/ne.dll?bh0bkyd2
> 
> After uninstall Skynet/Skynet Lite and reboot port scans are logged again.

We call this invalid packet logging in Skynet which can be toggled on/off via the settings menu (otherwise the packets will be dropped silently by the SPI firewall). Although in most cases you would want this disabled as it gets quite spammy;

`Oct 13 18:03:05 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=185.156.73.65 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=28402 PROTO=TCP SPT=62000 DPT=55650 SEQ=3496706884 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:06 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=183.88.48.165 DST=xxx.xxx.xxx.xxx LEN=60 TOS=0x00 PREC=0x00 TTL=45 ID=3641 DF PROTO=TCP SPT=32531 DPT=445 SEQ=160118803 ACK=0 WINDOW=8192 RES=0x00 SYN URGP=0 OPT (02040584010303020402080A0009680C00000000) M0
Oct 13 18:03:09 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=183.88.48.165 DST=xxx.xxx.xxx.xxx LEN=60 TOS=0x00 PREC=0x00 TTL=45 ID=4733 DF PROTO=TCP SPT=32531 DPT=445 SEQ=160118803 ACK=0 WINDOW=8192 RES=0x00 SYN URGP=0 OPT (02040584010303020402080A0009693800000000) M0
Oct 13 18:03:12 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=185.156.73.67 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=35179 PROTO=TCP SPT=62000 DPT=37070 SEQ=3108253041 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:14 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=45.129.33.82 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=14772 PROTO=TCP SPT=50242 DPT=6616 SEQ=447485112 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:16 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=45.146.167.215 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=243 ID=41734 PROTO=TCP SPT=62000 DPT=18595 SEQ=2256854897 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:25 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=79.124.62.34 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=241 ID=56807 PROTO=TCP SPT=53033 DPT=46780 SEQ=1293770639 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:25 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:26 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:26 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=45.129.33.128 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=2646 PROTO=TCP SPT=62000 DPT=28225 SEQ=3368112323 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:26 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:27 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=79.124.62.34 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=241 ID=30584 PROTO=TCP SPT=53033 DPT=8421 SEQ=1653891913 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:27 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:27 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:28 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:28 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=79.124.62.34 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=241 ID=65447 PROTO=TCP SPT=53033 DPT=51426 SEQ=3037660049 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:28 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:29 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:30 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:30 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=78 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=137 DPT=137 LEN=58 MARK=0x8000000
Oct 13 18:03:32 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=1900 DPT=1900 LEN=105 MARK=0x8000000
Oct 13 18:03:33 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=1900 DPT=1900 LEN=105 MARK=0x8000000
Oct 13 18:03:34 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=1900 DPT=1900 LEN=105 MARK=0x8000000
Oct 13 18:03:34 kernel: [BLOCKED - INBOUND] IN=ppp0 OUT= MAC= SRC=185.193.90.174 DST=xxx.xxx.xxx.xxx LEN=40 TOS=0x00 PREC=0x00 TTL=241 ID=34341 PROTO=TCP SPT=62000 DPT=36841 SEQ=788872472 ACK=0 WINDOW=1024 RES=0x00 SYN URGP=0 MARK=0x8000000
Oct 13 18:03:34 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=1900 DPT=1900 LEN=105 MARK=0x8000000
Oct 13 18:03:35 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=1900 DPT=1900 LEN=105 MARK=0x8000000
Oct 13 18:03:35 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=1900 DPT=1900 LEN=105 MARK=0x8000000
Oct 13 18:03:36 kernel: [BLOCKED - INVALID] IN=ppp0 OUT= MAC= SRC=4.79.142.206 DST=xxx.xxx.xxx.xxx LEN=125 TOS=0x00 PREC=0x00 TTL=226 ID=61440 PROTO=UDP SPT=1900 DPT=1900 LEN=105 MARK=0x8000000`



> (I had the idea to scan the logfile for **kernel: DROP** and make an auto block-list that will automatically expire after a certain time interval)

This was an original feature of Skynet called autoban, but we ended up removing it as some users would have issues with false positives.

**Comment by wbartels** [comment]
>We call this invalid packet logging in Skynet which can be toggled on/off via the settings menu

Thanks for the feedback!

> This was an original feature of Skynet called autoban, but we ended up removing it as some users would have issues with false positives.

I still will do some testing.
The code I came up with so far will only autoban an ip if this ip had used 10 or more different port numbers in 24 hour.
