### ISSUE TITLE
Some things to consider

### ISSUE THREAD

**Issue by Bengt-M** [Adamm00/IPSet_ASUS#6]
Thanks for a good work. I have explored several scripts an this is the one I like best.
I have found some things that I'm not completely happy about. Maybe you can consider.

I suggest you use ipset commands as described in the current man page, e.g use "add" instead of the old "-A". Much easier to understand.
Several times you use (ipset) -q when -! would be quite appropriate.
Something to wish for is to autoban the whole ISP and not just one IP (the serous attacker will have many IP's). I have not figured out how to do that, but sometimes I do it manually using whois.
That process would be much easier if the autobans had a separate ipset, also included in the Skynet group.

Whitelist_Shared
Please remove (already handled):
ipset -q -A Whitelist 192.168.1.0/24 comment "nvram: LAN Subnet"
Please add:
ipset -! add Whitelist "$(nvram get vpn_server1_sn)"/24 comment "nvram: vpn_server1_sn"
ipset -! add Whitelist "$(nvram get vpn_server2_sn)"/24 comment "nvram: vpn_server2_sn"
ipset -! add Whitelist "$(nvram get vpn_server_sn)"/24 comment "nvram: vpn_server_sn"

start
Please don't save the ipsets at start; It is very important to finish quickly. If the script takes too long time it may get called again and you will have two processes changing the iptables, with unpredictable result. (New behaviour in latest merlin release, at least on my router).
Better to just leave the saving to the cron script.
Why the sleep? I see no reason (and as above; it can create problems).

Unban_PrivateIP
Why this?
I blacklist the full range of all private subnets and whitelist my own subnets (from nvram as above). Whitelist is checked first so that should be the right way to do this.
(I have seen e.g. SRC=10.2.20.4 coming in on eth0. It should not be routed by my ISP but it's proper for me to just drop it.)

iptables
I suggest you apply the recommended pattern and do all filtering in the filter table. You could introduce a Skynet chain and do everything there, and have just one jump from somewhere in the input chain (on top, and you don't need to delete anything).
The raw table is not intended for filtering. Also, it's not reset to defaults when restarting the firewall service (as the filter table is), which makes it confusing.
And I don't agree with having the same filtering for outgoing and forward. Some filtering could be ok, just to behave sane and not send out bad packets, but absolutely not the same blacklist as for input.
(I might want to prevent US hackers to try my SSH, but I don't want to block all US web sites. Two very different problems that need different solutions, and I already use OpenDNS.)

I hope something here can be useful to you.
/BR

**Comment by Adamm00** [comment]
Thanks for the suggestions, let me try answer some.

> use "add" instead of the old "-A". 

More of a stylistic thing, but I'll keep it in mind.

> Several times you use (ipset) -q when -! would be quite appropriate.

The problem with the -! (ignore) flag is it overwrites existing entries, in some cases this is okay, but in others it can lead to other issues. In a lot of cases I don't want automated entries to overwrite manual entries as I'd like user input to be "permanent" in a sense. But in cases like banmalware, the performance loss of adding 150k ipset entries one by one via a for loop is not worth it. I'll go over the script at some point and see if there's any other instances where the ignore flag would be more appropriate.

> Please don't save the ipsets at start

Skynet will only run the save function on start during a fresh install where ipset.txt doesn't already exist (which takes under 1s in this case). This is to stop other errors from other functions as ipset.txt wouldn't exist yet.

>  If the script takes too long time it may get called again and you will have two processes changing the iptables, with unpredictable result.

This reason specifically is why I created the Check_Lock function. As firewall-start is executed twice during boot, I was having issues with race conditions (Skynet being executed and another instance being executed seconds later). Skynet for that reason will create a lockfile during specific commands (start being one of them), which potential conflicting commands will honor (the lock file must exist plus the process must still be active).

The forced sleep is because around 20s after firewall-start is executed for the first time, IPTables are flushed again. So a workaround was to try do as much work as possible during this time (besides modifying IPTables rules), then we can safely assume IPTables won't be flushed again so we modify the required rules.

> Something to wish for is to autoban the whole ISP and not just one IP

The issue here is false positives. In a lot of cases these bots are run off common shared hosting providers (or even home networks) which host thousands of legitimate IP's in the same subnets. I try to keep a fine balance between Skynet being adequately aggressive, but at the same time non intrusive. The last thing we want is less tech savvy users confused as to traffic is being potentially false flagged.

> Unban_PrivateIP - Why this?

This was a failsafe I added to prevent people accidentally locking themselves out, in earlier versions this was more necessary but not so much anymore. I'll consider removing this after I ask some other users if they have any hits from this function (thankfully with the comment extensions they are easily identified). If not I will add an option in the installer or something to bypass it.

> I suggest you apply the recommended pattern and do all filtering in the filter table

Initially this was how Skynet was designed. But ipset developers actually recommend using the raw table for performance gains so I switched over accordingly (you can find various tests if you search around, I posted a graph explaining this a few times on SNB). Long story short it bypasses contracking and additional processing by the kernel, so you make some noticeable performance gains. There is no real downside to using the raw table, its not really the intended purpose of the table, but I think the benefits outweigh the "unconventional" usage.

> Also, it's not reset to defaults when restarting the firewall service (as the filter table is), which makes it confusing.

Skynet is designed to handle this situation, and avoid duplicates etc. One of my main priorities was to make Skynet "unbreakable" in a sense so that there is no possible way using Skynet alone you can end up with duplicate entries/missing/wrongly positioned rules. If you can find a way to break it, I'll be more then happy to fix it.

> And I don't agree with having the same filtering for outgoing and forward. Some filtering could be ok, just to behave sane and not send out bad packets, but absolutely not the same blacklist as for input.

Initially I only had incoming packets blocked, but after lots of user feedback the most common request was I also block outgoing packets. Unfortunately there's not much of a middle ground here beyond be specific with what you block. But I'm always open to suggestions.


> Please remove (already handled):

Again this was another failsafe I left in from earlier (dumber) Skynet versions. I can definitely see the case against removing it as this should be handled by the nvram value "lan_ipaddr", but I also didn't want to accidentally ignore some edge case where this subnet could be used by something else and have a bunch of users complain they got locked out of their router because of it. I will definitely consider it in future versions if I can't find any obvious use cases.


> Please add:

This was on my to-do list finding any VPN specific nvram values (thanks for sharing), I just never had a VPN to test with. I'll add these values now and will look into getting a VPN to tinker with. I know astrill has a good relationship with RMerlin so maybe they can provide a "dev" account. Thanks for the reminder, this should be added by the time you see this reply so just initiate a forced update.

Thanks for the feedback, if I missed anything else let me know, always happy to help!
